### ISSUE TITLE
Ember Inspector `Data` tab is throwing an error

### ISSUE THREAD

**Issue by petrosp** [pixelhandler/ember-jsonapi-resources#127]
Hi there!

I have been running the `dummy` app included in the repo and whenever I press on the `Data` tab of Ember Inspector I get this error:

- Firefox  
```
"Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: adapter is undefined
Stack trace: exports.default<.adapter<@eval:680:7
ComputedPropertyPrototype.get@http://localhost:4200/assets/vendor.js:29087:15
get@http://localhost:4200/assets/vendor.js:33959:14
exports.default<.get@http://localhost:4200/assets/vendor.js:46983:14
checkAdapter@eval:814:56
sendEvent@http://localhost:4200/assets/vendor.js:29952:11
exports.default<.trigger@http://localhost:4200/assets/vendor.js:46262:7
messageReceived/<@eval:3603:9
wrap/<@eval:3633:18
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10829:18
run@http://localhost:4200/assets/vendor.js:34263:12
wrap@eval:3631:14
messageReceived@eval:3602:7
init/<@eval:3594:11
_messageReceived/<@eval:131:9
_messageReceived@eval:130:7
_listen/</<@eval:419:11
Backburner.prototype.run@http://localhost:4200/assets/vendor.js:10829:18
run@http://localhost:4200/assets/vendor.js:34263:12
_listen/<@eval:406:9
"
```

- Chrome
```
VM131:96 Ember Inspector has errored.
This is likely a bug in the inspector itself.
You can report bugs at https://github.com/emberjs/ember-inspector.
Error message: Cannot read property 'set' of undefined
Stack trace: TypeError: Cannot read property 'set' of undefined
    at Class.<anonymous> (<anonymous>:680:14)
    at ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:29087:28)
    at Object.get (http://localhost:4200/assets/vendor.js:33959:19)
    at Class.get (http://localhost:4200/assets/vendor.js:46983:38)
    at Class.checkAdapter (<anonymous>:814:61)
    at Object.sendEvent (http://localhost:4200/assets/vendor.js:29952:18)
    at Class.trigger (http://localhost:4200/assets/vendor.js:46262:25)
    at <anonymous>:3603:16
    at Class.<anonymous> (<anonymous>:3633:18)
    at Backburner.run (http://localhost:4200/assets/vendor.js:10829:25)warn @ VM131:96handleError @ VM131:153(anonymous function) @ VM131:3635run @ ember.debug.js:294run @ ember.debug.js:23728wrap @ VM131:3631messageReceived @ VM131:3602(anonymous function) @ VM131:3594(anonymous function) @ VM131:131_messageReceived @ VM131:130(anonymous function) @ VM131:324run @ ember.debug.js:294run @ ember.debug.js:23728(anonymous function) @ VM131:323
```

Is this by design or you think truly an `Inspector` issue -- it does run correctly for the rest of my `ember` apps.

Thanks!

Petros

**Comment by petrosp** [comment]
Hmm, based on this [Glitter talk](https://gitter.im/pixelhandler/ember-jsonapi-resources/archives/2015/09/16), you suggested that `inpector` is designed for `ember-data` only. Closing.

**Comment by pixelhandler** [comment]
@petrosp I'll take a look
